# Generated by Django 2.2.4 on 2019-09-08 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SocialPlatform'),
        ),
        migrations.AlterField(
            model_name='user',
            name='social_user_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
