# Generated by Django 2.2.4 on 2019-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=15, unique=True)),
                ('user_name', models.CharField(max_length=15, null=True)),
                ('user_password', models.CharField(max_length=200, null=True)),
                ('user_email', models.EmailField(max_length=50, null=True, unique=True)),
                ('user_photo', models.URLField(null=True)),
                ('user_profile', models.CharField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
