# Generated by Django 2.2.4 on 2019-09-04 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_no', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('method', models.CharField(max_length=2000)),
                ('image', models.URLField(max_length=300, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoryItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.CategoryItem')),
            ],
        ),
    ]
