# Generated by Django 2.2.4 on 2019-09-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_auto_20190907_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeitem',
            old_name='recipe_no',
            new_name='recipe_number',
        ),
    ]
