# Generated by Django 2.2.4 on 2019-08-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190829_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='news',
            table='title',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tag',
        ),
    ]
